# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Film for Change NZ
email: info@filmforchange.org.nz
description: > # this means to ignore newlines until "baseurl:"
  Film for Change is a charity that makes films for other charities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://filmforchange.org.nz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
